import type { Config } from "tailwindcss";
import type { PluginUtils } from "tailwindcss/types/config"

const config = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        letterSpacing: {
            tighter: '-0.0937500rem',
            tight: '-0.0312500rem',
            normal: '0rem',
            wide: '0.0062500rem',
            wider: '0.0093750rem',
            widest: '0.0156250rem',
            'x-wide': '0.0250000rem',
            '2x-wide': '0.0312500rem',
            '3x-wide': '0.0781250rem',
            '4x-wide': '0.0937500rem'
        },
        fontSize: {
            '2xs': '0.75rem',
            xs: '0.875rem',
            sm: '0.9375rem',
            base: '1rem',
            lg: '1.0625rem',
            xl: '1.125rem',
            '2xl': '1.375rem',
            '3xl': '1.625rem',
            '4xl': '2.3125rem',
            '5xl': '3.25rem',
            '6xl': '4.0625rem',
            '7xl': '6.5rem',
        },

        extend: {
            fontFamily: {
                jost: ['var(--font-jost)'],
                spaceGrotesk: ['var(--font-space-grotesk)'],
            },


            /*########## RETURN TO HERE TO EDIT COLORS*/
            typography: ({ theme }: PluginUtils) => ({
                DEFAULT: {
                    css: {
                        '--tw-prose-body': 'var(--custom-prose-body)',
                        '--tw-prose-headings': 'var(--custom-prose-headings)',
                        '--tw-prose-lead': 'var(--custom-prose-lead)',
                        '--tw-prose-links': 'var(--custom-prose-links)',
                        '--tw-prose-bold': 'var(--custom-prose-bold)',
                        '--tw-prose-counters': 'var(--custom-prose-counters)',
                        '--tw-prose-bullets': 'var(--custom-prose-bullets)',
                        '--tw-prose-hr': 'var(--custom-prose-hr)',
                        '--tw-prose-quotes': 'var(--custom-prose-quotes)',
                        '--tw-prose-quote-borders': 'var(--custom-prose-quote-borders)',
                        '--tw-prose-captions': 'var(--custom-prose-captions)',
                        '--tw-prose-code': 'var(--custom-prose-code)',
                        '--tw-prose-pre-code': 'var(--custom-prose-pre-code)',
                        '--tw-prose-pre-bg': 'var(--custom-prose-pre-bg)',
                        '--tw-prose-th-borders': 'var(--custom-prose-th-borders)',
                        '--tw-prose-td-borders': 'var(--custom-prose-td-borders)',
                    },
                },
            }),

            colors: {
                transparent: 'transparent',
                current: 'currentColor',
                'primary': 'var(--primary)',
                'surface-tint': 'var(--surface-tint)',
                'on-primary': 'var(--on-primary)',
                'primary-container': 'var(--primary-container)',
                'on-primary-container': 'var(--on-primary-container)',
                'secondary': 'var(--secondary)',
                'on-secondary': 'var(--on-secondary)',
                'secondary-container': 'var(--secondary-container)',
                'on-secondary-container': 'var(--on-secondary-container)',
                'tertiary': 'var(--tertiary)',
                'on-tertiary': 'var(--on-tertiary)',
                'tertiary-container': 'var(--tertiary-container)',
                'on-tertiary-container': 'var(--on-tertiary-container)',
                'error': 'var(--error)',
                'on-error': 'var(--on-error)',
                'error-container': 'var(--error-container)',
                'on-error-container': 'var(--on-error-container)',
                'background': 'var(--background)',
                'on-background': 'var(--on-background)',
                'surface': 'var(--surface)',
                'on-surface': 'var(--on-surface)',
                'surface-variant': 'var(--surface-variant)',
                'on-surface-variant': 'var(--on-surface-variant)',
                'outline': 'var(--outline)',
                'outline-variant': 'var(--outline-variant)',
                'shadow': 'var(--shadow)',
                'scrim': 'var(--scrim)',
                'inverse-surface': 'var(--inverse-surface)',
                'inverse-on-surface': 'var(--inverse-on-surface)',
                'inverse-primary': 'var(--inverse-primary)',
                'primary-fixed': 'var(--primary-fixed)',
                'on-primary-fixed': 'var(--on-primary-fixed)',
                'primary-fixed-dim': 'var(--primary-fixed-dim)',
                'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
                'secondary-fixed': 'var(--secondary-fixed)',
                'on-secondary-fixed': 'var(--on-secondary-fixed)',
                'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
                'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
                'tertiary-fixed': 'var(--tertiary-fixed)',
                'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
                'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
                'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
                'surface-dim': 'var(--surface-dim)',
                'surface-bright': 'var(--surface-bright)',
                'surface-container-lowest': 'var(--surface-container-lowest)',
                'surface-container-low': 'var(--surface-container-low)',
                'surface-container': 'var(--surface-container)',
                'surface-container-high': 'var(--surface-container-high)',
                'surface-container-highest': 'var(--surface-container-highest)',
                'border': 'hsl(var(--border))',
                'input': "hsl(var(--input))",
                'ring': "hsl(var(--ring))",
                /*background: "hsl(var(--background))",*/
                'foreground': "hsl(var(--foreground))",

                //primary: {
                //    DEFAULT: "hsl(var(--primary))",
                //    foreground: "hsl(var(--primary-foreground))",
                //},
                //secondary: {
                //    DEFAULT: "hsl(var(--secondary))",
                //    foreground: "hsl(var(--secondary-foreground))",
                //},
                'destructive': {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                'muted': {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                'accent': {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                'popover': {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                'card': {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                'neon-orange': {
                    '50': '#fff8ed',
                    '100': '#ffefd4',
                    '200': '#ffdba8',
                    '300': '#ffc171',
                    '400': '#ffa144',
                    '500': '#fe7d11',
                    '600': '#ef6207',
                    '700': '#c64808',
                    '800': '#9d3a0f',
                    '900': '#7e3110',
                    '950': '#441606',
                },
                'aquamarine': {
                    '50': '#e9fff7',
                    '100': '#caffe9',
                    '200': '#99ffda',
                    '300': '#5dfdcb',
                    '400': '#17f0b3',
                    '500': '#00d89d',
                    '600': '#00b082',
                    '700': '#008d6c',
                    '800': '#006f56',
                    '900': '#005b49',
                    '950': '#00342a',
                },
                'mauve': {
                    '50': '#fbf5ff',
                    '100': '#f6e8ff',
                    '200': '#eed4ff',
                    '300': '#e0b0ff',
                    '400': '#cf82fe',
                    '500': '#bc53f9',
                    '600': '#aa31ec',
                    '700': '#9320d0',
                    '800': '#7c1faa',
                    '900': '#651b88',
                    '950': '#470665',
                },
                'marshland': {
                    '50': '#f7f7f6',
                    '100': '#e7e7e0',
                    '200': '#cdcec1',
                    '300': '#acae9a',
                    '400': '#898c75',
                    '500': '#6d715b',
                    '600': '#575a47',
                    '700': '#474a3b',
                    '800': '#3b3d32',
                    '900': '#34352c',
                    '950': '#12130f',
                },
                'spicy-pink': {
                    '50': '#f4f3f2',
                    '100': '#e4dfdd',
                    '200': '#cac2be',
                    '300': '#ac9d98',
                    '400': '#94807b',
                    '500': '#85716d',
                    '600': '#7a6563',
                    '700': '#5c4d4c',
                    '800': '#504344',
                    '900': '#473c3d',
                    '950': '#272122',
                },
            },

            container: {
                center: true,
            },

            dropShadow: {
                'harsh': '0 3px 0 rgb(0, 0, 0, 1)',
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        }
    },
    plugins:
        [require("tailwindcss-animate"),
        require('@tailwindcss/typography')],
} satisfies Config

export default config;
