import type { Metadata } from "next";
import { Jost, Space_Grotesk } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/app/components/MainNavigation";
import ContentWrapper from "@/app/components/ContentWrapper";
import { Providers } from './providers';

const space_grotesk = Space_Grotesk({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-space-grotesk',
});


const jost = Jost({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-jost',
});

export const metadata: Metadata = {
  title: "Analytic Talesmith",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`${space_grotesk.variable} ${jost.variable}`}  suppressHydrationWarning>
            <body className='bg-background dark:bg-background-d'>
            <Providers>
                < MainNavigation />
                <ContentWrapper>
                      <div className="font-jost bg-primary dark:bg-primary-d text-on-primary dark:text-on-primary-d">{children}</div>
                </ContentWrapper>
            </Providers>  
          </body>
    </html>
  );
}