import type { Metadata } from "next";
import { Jost, Space_Grotesk } from "next/font/google";
import "@/app/styles/globals.css";
import MainNavigation from "@/app/components/MainNavigation";
import ContentWrapper from "@/app/components/ContentWrapper";
import { ThemeProvider }  from "@/app/components/ThemeProvider";

const space_grotesk = Space_Grotesk({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-space-grotesk',
});


const jost = Jost({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-jost',
});

export const metadata: Metadata = {
  title: "Analytic Talesmith",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`${space_grotesk.variable} ${jost.variable}`}  suppressHydrationWarning>
            <body className='bg-background'>
            <ThemeProvider>
                < MainNavigation />
                <ContentWrapper>
                      <div className="font-jost bg-primary text-on-primary ">{children}</div>
                </ContentWrapper>
            </ThemeProvider>  
          </body>
    </html>
  );
}